modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "thiocyanate"
version = "${version}"
displayName = "Thiocyanate"
authors = "Survivalblock\nAlcatrazEscapee"
description = "SCN - a modern port of Cyanide"
logoFile = "assets/thiocyanate/icon.png"
issueTrackerURL = "https://github.com/ekulxam/thiocyanate/issues"
displayURL="https://modrinth.com/mod/thiocyanate"
modURL="https://modrinth.com/mod/thiocyanate"

[[dependencies.thiocyanate]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thiocyanate]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft}]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "thiocyanate.mixins.json"