modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "thiocyanate_test"
version = "${version}"
displayName = "Thiocyanate Testmod"
authors = "Survivalblock, AlcatrazEscapee"
description = '''
'''

[[dependencies.thiocyanate_test]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thiocyanate_test]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft}]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "thiocyanate_test.mixins.json"